### ISSUE TITLE
Touch Outside Dismiss 

### ISSUE THREAD

**Issue by YouSour** [marcos930807/awesomeDialogs#101]
hi , why touch outside to dismiss it keeping pop my current page, any idea ?
**implement** : 
```
import 'package:awesome_dialog/awesome_dialog.dart';
import 'package:flutter/material.dart';

class Alert {
  static show({
    required String desc,
    required BuildContext context,
    DialogType dailogType = DialogType.SUCCES,
    Duration autoHide = const Duration(seconds: 5),
  }) {
    return AwesomeDialog(
      context: context,
      dialogType: dailogType,
      headerAnimationLoop: false,
      animType: AnimType.TOPSLIDE,
      autoHide: autoHide,
      width: 500,
      aligment: const Alignment(0.0, -0.9),
      barrierColor: Colors.transparent,
      title: dailogType.name,
      desc: desc,
    ).show();
  }
}
```
**version** : awesome_dialog: ^2.2.0
**problem** : [https://drive.google.com/file/d/11gaFXAia6-3kb5K36MMG55UHwktLzkAa/view?usp=sharing](https://drive.google.com/file/d/11gaFXAia6-3kb5K36MMG55UHwktLzkAa/view?usp=sharing)

**Comment by marcos930807** [comment]
That depend on which context do you use for showing the dialog, my advice is that try using the prop useRootNavigator.

**Comment by YouSour** [comment]
@marcos930807 i try with useRootNavigator still not work.

**Comment by OutdatedGuy** [comment]
Hey, @YouSour I think I understood the issue. I'll try to fix the issue as soon as possible.
Thanks for the report.
