### ISSUE TITLE
Error in new Flutter 3

### ISSUE THREAD

**Issue by skylastn** [marcos930807/awesomeDialogs#107]
../../../../System/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:167:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../System/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.cancelFrameCallbackWithId(_frameCallbackID);
                         ^
../../../../System/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:170:28: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../System/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance?.scheduleFrameCallback(_beginFrame) ?? -1;
                           ^
../../../../System/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:272:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../System/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.cancelFrameCallbackWithId(_frameCallbackID);

**Comment by MuhammadMahrash** [comment]
Same issue

**Comment by salahmusamac** [comment]
@marcos930807 
use this
dependency_overrides:
  flare_flutter :
    git:
      url: https://github.com/mdpe-ir/Flare-Flutter
      path: flare_flutter
      ref: stable

**Comment by tungvt80** [comment]
Nok work . When they fixed i will update de version of dependency.

**Comment by tripany** [comment]
@marcos930807 

Flare is not maintained anymore. You have to migrate to Rive instead.

See https://github.com/2d-inc/Flare-Flutter

**Comment by marcos930807** [comment]
> @marcos930807
> 
> Flare is not maintained anymore. You have to migrate to Rive 2 instead.
> 
> See https://github.com/2d-inc/Flare-Flutter

There is no easy migration from flare to Rive. Rive 2 is not fully backguard compatible, i do not have time to recreate al animation in rive2. So by now i will be using dependency override for the flare package pointing to a PR with the Fix.

**Comment by EhabSalah** [comment]
Any updates?

**Comment by Ruslanbek0809** [comment]
If you still get issue using dependency override put it like this:
```
dependency_overrides:
  flare_flutter :
    git:
      url: https://github.com/mdpe-ir/Flare-Flutter
      path: flare_flutter
      ref: stable
```

**Comment by marcos930807** [comment]
The version 3.0 is out with new Rive runtime for animation a some other changes. Now the problem is gone.
