### ISSUE TITLE
Please update to the new dependency package。

### ISSUE THREAD

**Issue by Junesui** [marcos930807/awesomeDialogs#111]
Please update to the new dependency package。

----------------
flare_flutter:
    git:
      url: https://github.com/tsinis/Flare-Flutter

**Comment by marcos930807** [comment]
Publishable package can only have dependency from pub.dev

**Comment by Junesui** [comment]
.

**Comment by marcos930807** [comment]
@Junesui version 3.0 is out with new Rive runtime.
