### ISSUE TITLE
Temporary remove QUESTION

### ISSUE THREAD

**Issue by fggluiz** [marcos930807/awesomeDialogs#115]
_[Breaking] Temporary remove QUESTION type header for being incompatible with rive._

Do you have any predictions on how much you will implement the QUESTION option?
My application uses it in multiple places.

**Comment by idish** [comment]
Same here, I'll be needing to revert to older version as the question type is important for me.

**Comment by fggluiz** [comment]
Hello Marco. I imported an old question file (Flare -> Rive 2). Check if it is correct.

[question.zip](https://github.com/marcos930807/awesomeDialogs/files/9634497/question.zip)

**Comment by marcos930807** [comment]
> Hello Marco. I imported an old question file (Flare -> Rive 2). Check if it is correct.
> 
> [question.zip](https://github.com/marcos930807/awesomeDialogs/files/9634497/question.zip)

Can you please share a backup of this animation so i can change some things like anime name, background to transparent aspect ratio etc. You can do that by exporting a .rev file

**Comment by fggluiz** [comment]
> > Hello Marco. I imported an old question file (Flare -> Rive 2). Check if it is correct.
> > [question.zip](https://github.com/marcos930807/awesomeDialogs/files/9634497/question.zip)
> 
> Can you please share a backup of this animation so i can change some things like anime name, background to transparent aspect ratio etc. You can do that by exporting a .rev file

Yes! 
[question.zip](https://github.com/marcos930807/awesomeDialogs/files/9636177/question.zip)

**Comment by marcos930807** [comment]
ok thanks @fggluiz  i will test this and let you known later.

**Comment by marcos930807** [comment]
@idish @fggluiz Version 3.0.2 is out with question type support again thanks @fggluiz
