### ISSUE TITLE
Getting error on btnOkOnPress and btnCancelOnPress: 

### ISSUE THREAD

**Issue by FarhanSaikh** [marcos930807/awesomeDialogs#12]
getting error on click btnOkOnPress and
              btnCancelOnPress: 

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following StateError was thrown while handling a gesture:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
#1      Route.didComplete (package:flutter/src/widgets/navigator.dart:208:19)
#2      Route.didPop (package:flutter/src/widgets/navigator.dart:196:5)
#3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:62:36)
#4      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:218:18)
#5      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:552:18)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#59e0d
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(133.0, 455.5)
  finalLocalPosition: Offset(68.0, 28.0)
  button: 1
  sent tap down

**Comment by haydenlak** [comment]
Try adding this line:

AwesomeDialog(context: context,
**useRootNavigator: true,**
 dialogType: DialogType.INFO,
...

**Comment by yhatibi** [comment]
> AwesomeDialog

Worked for me, thanks!
