### ISSUE TITLE
How do I make AwesomeDialog a stateful widget?

### ISSUE THREAD

**Issue by haydenlak** [marcos930807/awesomeDialogs#13]
I am trying to update a widget inside AwesomeDialog using setState but only the main widget tree gets updated. Is there a way to make AwesomeDialog stateful as well?

**Comment by marcos930807** [comment]
Hi @haydenlak, body of awesomeDialog is a Widget make it Stateful to update the body content as you wish, or use Bloc, ChangeNotifier, wathever to manage the state.

**Comment by fabiancrx** [comment]
@haydenlak you could also use a StatefulBuilder
