### ISSUE TITLE
 Significant increase in Android app size (solution)

### ISSUE THREAD

**Issue by SalahAnwer** [marcos930807/awesomeDialogs#138]
Upgrade rive package to latest version to solve this issue. Details [(here)](https://github.com/rive-app/rive-flutter/issues/347#issuecomment-1979496123).

**Comment by MajdSallora** [comment]
I update the rive package to latest version but same thing, so I downgrade to another version

```
  awesome_dialog:
    git:
      url: https://github.com/MajdSallora/awesomeDialogs.git
```

**Comment by marcos930807** [comment]
> Upgrade rive package to latest version to solve this issue. Details [(here)](https://github.com/rive-app/rive-flutter/issues/347#issuecomment-1979496123).

Tnaks

**Comment by marcos930807** [comment]
using this version of NDK is Mandatory android {
    ...
    ndkVersion '25.1.8937393'
}
