### ISSUE TITLE
Automatically hide dialog when timed out

### ISSUE THREAD

**Issue by honghai2196** [marcos930807/awesomeDialogs#14]
Hi marcos,

I would like to ask you how can I hide dialog automatically for timed out (i.e 3 seconds from dialog appear).

Thank you very much.

**Comment by marcos930807** [comment]
Hi @honghai2196 
You can achieve this by saving the AwesomeDialog instance and calling the dissmiss method at a certain time.
Example:
showDialogFor3Seconds() async {
    AwesomeDialog dialog = AwesomeDialog(
      context: context,
      dialogType: DialogType.INFO,
      animType: AnimType.BOTTOMSLIDE,
      tittle: 'Hi',
      desc: 'I am Here for only for 3 seconds',
    );
    dialog.show();
    await Future.delayed(Duration(seconds: 3));
    dialog.dissmiss();
  }
Hope That Helps, closing for now feel free to reopen.

**Comment by marcos930807** [comment]
Just for Future references now exist a prop AutoHide that do exactly this.
