### ISSUE TITLE
Error to call dissmiss() method 

### ISSUE THREAD

**Issue by ifranciscoglez** [marcos930807/awesomeDialogs#15]
Hello, can someone help me, I am trying to use the onDissmissCallBack parameter but I am getting an error. This is my code.

`  AwesomeDialog awesomeDialog;`

`AwesomeDialog(context: context,`
           ` dialogType: DialogType.INFO,`
           ` animType: AnimType.BOTTOMSLIDE,`
            `tittle: 'Dialog Title',`
           ` useRootNavigator: true,`
       `     desc: 'Dialog description here',`
        `    dismissOnTouchOutside: false,`
           ` onDissmissCallback: (){`
                        `      debugPrint('Dialog Dissmiss from callback');`
                    `          awesomeDialog.dissmiss();`
       `     },`
           ` btnCancelOnPress: () {},`
        ` btnOkOnPress: () {}).show();`

And this is the error that I get

I/flutter (30505): Dialog Dissmiss from callback
E/flutter (30505): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'dissmiss' was called on null.
E/flutter (30505): Receiver: null
E/flutter (30505): Tried calling: dissmiss()
E/flutter (30505): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter (30505): #1      _UpdatePasswordState._onChangePassword.<anonymous closure> 
package:alerta_acapulco_app/…/settings/update_password_page.dart:177
E/flutter (30505): #2      AwesomeDialog.show.<anonymous closure> 
package:awesome_dialog/awesome_dialog.dart:95
E/flutter (30505): #3      _rootRunUnary  (dart:async/zone.dart:1155:38)
E/flutter (30505): #4      _CustomZone.runUnary  (dart:async/zone.dart:1048:19)
E/flutter (30505): #5      _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (30505): #6      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (30505): #7      Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (30505): #8      Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (30505): #9      Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:556:7)
E/flutter (30505): #10     _rootRun  (dart:async/zone.dart:1147:13)
E/flutter (30505): #11     _CustomZone.run  (dart:async/zone.dart:1040:19)
E/flutter (30505): #12     _CustomZone.runGuarded  (dart:async/zone.dart:942:7)
E/flutter (30505): #13     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:982:23)
E/flutter (30505): #14     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (30505): #15     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)

Thank you

**Comment by marcos930807** [comment]
First you need to asign the instance of Awesome Dialog (note the cascade operator to retrive the dialog instance ):

var awesomeDialog = AwesomeDialog(context: context,
dialogType: DialogType.INFO,
animType: AnimType.BOTTOMSLIDE,
tittle: 'Dialog Title',
desc: 'Dialog description here',
dismissOnTouchOutside: false,
btnCancelOnPress: () {},
btnOkOnPress: () {})..show();

The you can dissimiss that instance any time you want, like this:
awesomeDialog.dissmiss();
The onDissmissCallback: is a function that will be executed after the dialog get dissmissed.

If you want more help ask mo problem.

**Comment by ifranciscoglez** [comment]
Thank you Marcos 👍
