### ISSUE TITLE
Error: The getter 'headline6' isn't defined for the class 'TextTheme'

### ISSUE THREAD

**Issue by chounry** [marcos930807/awesomeDialogs#18]
The error message when trying to run the project :

Compiler message:
../../../flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_dialog-1.1.0/lib/src/vertical_stack_header_dialog.dart:60:66: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter-sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                              style: Theme.of(context).textTheme.headline6,
                                                                 ^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

**Package version :** 
awesome_dialog: ^1.1.0

**Comment by marcos930807** [comment]
If you upgrade to latest flutter stable run flutter clean:wink:

**Comment by chounry** [comment]
yes, i just upgraded

**Comment by marcos930807** [comment]
i will close it now feel free to reopen. thanks
