### ISSUE TITLE
How do I  scroll dialog which use TextField in body property when Keyboard showed.

### ISSUE THREAD

**Issue by shuheu** [marcos930807/awesomeDialogs#19]
As I said at this issues title, How do I  scroll dialog which use TextField in body property when Keyboard showed?

I'm trying to use TextField in a body property.
I focus TextField input area, Keyboard is showed up, the dialog is being under the keyboard.

Thank you:)

**Comment by marcos930807** [comment]
Hi shuheu, you can set dialog aligment topCenter to avoid dialog under the keyboard, later a will see if find a more proper Solution.:innocent:

**Comment by shuheu** [comment]
Hi! marcos930807, Thank you for your quick reply🙇‍♂️ 
I tried using topCenter, surely the dialog isn't covered from the keyboard.
The dialog which has alignment topCenter is a little too high position😭
I'd like to be a position which is more bottom if it is possible.

**Comment by marcos930807** [comment]
Hi @shuheu the new version 1.1.1 released now cover the feature you need. You dont need to do anything just left the gravity by default, The Dialog now is aware of keyboard and scrool himself.
