### ISSUE TITLE
determining whether dialog was dismissed via cancel or ok

### ISSUE THREAD

**Issue by yaizudamashii** [marcos930807/awesomeDialogs#20]
Currently the only way to determine if the AwesomeDialog instance was dismissed because of ok button press is by keeping a state in the presenting widget and referring it to onDissmissCallback.  It will be great if onDismissCallback can supply the close path of the dialog, maybe as an enum value.

**Comment by GreenHatHG** [comment]
Could you please tell me how to achieve this? Now I need to verify to close the dialog after clicking OK

**Comment by marcos930807** [comment]
Hi @yaizudamashii this is DONE on 2.1.0.
