### ISSUE TITLE
How to rebuild body of dialog ?

### ISSUE THREAD

**Issue by amegos** [marcos930807/awesomeDialogs#21]
It's possible to rebuild body of dialog, if yes how can I do that ?? because seState({}); doesn't work with me. please help.

**Comment by marcos930807** [comment]
Hi @amegos  you need to make body of AwesomeDialog a StateFullWidget and call setState inside of it. Hope that Help.

**Comment by amegos** [comment]
Thank you it's worked perfectly 👌
