### ISSUE TITLE
Why AwesomeDialog is not a Widget?

### ISSUE THREAD

**Issue by Setti7** [marcos930807/awesomeDialogs#22]
I'm trying to use your package together with [Get](https://pub.dev/packages/get), but for it to show a dialog (with `Get.dialog`) it needs to be a Widget. So, is there a reason you chose to not make AwesomeDialog a widget?

**Comment by marcos930807** [comment]
After reading the Get documentation I can see that with Get.context you can get the context to use  in Awesome dialog although I don't particularly like to put the logic of dialogs inside the bussinesLogic someTime save times so, you could do:

AwesomeDialog(
            context: Get.context,
            dialogType: DialogType.INFO,
            animType: AnimType.BOTTOMSLIDE,
            title: 'Dialog Title',
            desc: 'Dialog description here.............',
            btnCancelOnPress: () {},
            btnOkOnPress: () {},
            )..show();

**Comment by Setti7** [comment]
Thanks!
