### ISSUE TITLE
Not refresh the value if date updated

### ISSUE THREAD

**Issue by function2000** [marcos930807/awesomeDialogs#24]
If I use RadioListTile in the body, and when update the value, it does not update on the screen.  Looks it is stateless widget.  Can you make it possible to refresh value on the screen.

**Comment by marcos930807** [comment]
hi @function2000 make body a StateFull Widget and call setState inside of it., or use Change Notifier With Provider. or other state management solution.

**Comment by function2000** [comment]
Thanks!
