### ISSUE TITLE
add enable and disable buttons options for Ok and Cancel btn - improvements

### ISSUE THREAD

**Issue by robertoltrocha** [marcos930807/awesomeDialogs#26]
Hi, 
I would like to thank you for your package and would like to ask if it is possible to include the option of enable and disable for the buttons?
I would like to enable and disable the buttons under some conditions.
For example, after clicking on a checkbox agreeing to the terms, the Ok button would be enabled.

**Comment by marcos930807** [comment]
hi @robertoltrocha for the moment a workaround could be have your own buttons inside the body make it stateFull Widget and manage yourselve the logic to enabe and disable those button on certain events.

**Comment by robertoltrocha** [comment]
thanks for your answer and workaround. I will do this.
