### ISSUE TITLE
Dialog width expanded on flutter web

### ISSUE THREAD

**Issue by ishangavidusha** [marcos930807/awesomeDialogs#27]
How can I prevent dialog expending on flutter web?

![awesome_dialog](https://user-images.githubusercontent.com/23151210/86765334-fdd40200-c083-11ea-80e6-0b583ceb1f42.JPG)

Doctor summary :
> [√] Flutter (Channel master, 1.20.0-2.0.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.46.1)
[√] Connected device (3 available)

**Comment by marcos930807** [comment]
Hi @ishangavidusha currently by design the dialog occupies the width of the screen minus a margin, later a will add a prop to customize this, stay tuned.

**Comment by marcos930807** [comment]
hi @ishangavidusha sorry for delay, check version 1.2.0

**Comment by ishangavidusha** [comment]
> hi @ishangavidusha sorry for delay, check version 1.2.0

Nice,  I'll check and update to the latest version. Thank You.
