### ISSUE TITLE
Unable to load assets

### ISSUE THREAD

**Issue by Crypt0Graphic** [marcos930807/awesomeDialogs#28]
Dialog works normally but icons does not shown. I get this error:

```
Unhandled Exception: Unable to load asset: packages/awesome_dialog/assets/flare/succes_without_loop.flr
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetFlare.load (package:flare_flutter/provider/asset_flare.dart:26:31)
#2      FlareCacheAsset.load (package:flare_flutter/flare_cache_asset.dart:30:19)
#3      Cache.getAsset (package:flare_flutter/cache.dart:58:11)
#4      cachedActor (package:flare_flutter/flare_cache.dart:27:12)
#5      FlareRenderBox.loadFlare (package:flare_flutter/flare_render_box.dart:308:35)
#6      FlareActorRenderObject.coldLoad (package:flare_flutter/flare_actor.dart:410:20)
#7      FlareRenderBox.load (package:flare_flutter/flare_render_box.dart:258:7)
#8      FlareRenderBox.attach (package:flare_flutter/flare_render_box.dart:104:7)
#9      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
#10     RenderObject.adoptChild (package:flutter/src<…>
```

Flutter Doctor Results

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.1)
[✓] Connected device (1 available)

**Comment by Crypt0Graphic** [comment]
Restarting Emulator fixed it.

**Comment by marcos930807** [comment]
Closing for now .

**Comment by afaqueali97** [comment]
Got a similar issue with awesome dialog.
"
E/flutter ( 3576): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "packages/awesome_dialog/assets/flare/error_without_loop.flr".
E/flutter ( 3576): The asset does not exist or has empty data.
E/flutter ( 3576): #0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:324:9)
E/flutter ( 3576): <asynchronous suspension>
E/flutter ( 3576): #1      FlareCacheAsset.load.<anonymous closure> (package:flare_flutter/flare_cache_asset.dart:21:31)
E/flutter ( 3576): <asynchronous suspension>
"
