### ISSUE TITLE
single OK button get a sizebox on left

### ISSUE THREAD

**Issue by The-five-stooges** [marcos930807/awesomeDialogs#3]
`btnCancel != null
                                ? Expanded(
                                    child: btnCancel ?? Container(),
                                  )
                                : Container(),
                            SizedBox(
                              width: 10,
                            ),
                            btnOk != null
                                ? Expanded(
                                    child: btnOk,
                                  )
                                : Container(),`
thanks for you awesome work! 👍  
there has a little suggestion:
when there is only a single button, the sizedbox should be invisible

**Comment by marcos930807** [comment]
Tanks for raise an issue i will uplaod now the suggestion

**Comment by marcos930807** [comment]
This is fixed on 0.1.0
