### ISSUE TITLE
add x on top corner to close 

### ISSUE THREAD

**Issue by owengiri20** [marcos930807/awesomeDialogs#31]
if we could have a feature like this it would be great (:
i need one asap

**Comment by owengiri20** [comment]
![photo_2020-08-12_14-53-29](https://user-images.githubusercontent.com/46738862/89984211-9aa14500-dcab-11ea-80db-e1d07a875d98.jpg)
something like this

**Comment by marcos930807** [comment]
Hi @owengiri20 this is now implemented via pr #50.
