### ISSUE TITLE
Set max width of the dialog box

### ISSUE THREAD

**Issue by johnareid54** [marcos930807/awesomeDialogs#32]
Is it possible to set the maximum width of the dialog box?
When running on FlutterWeb on a normal computer screen the dialog is very large.

**Comment by marcos930807** [comment]
I will work on this soon stay tuned.

**Comment by marcos930807** [comment]
@johnareid54 check version 1.2.0.

**Comment by johnareid54** [comment]
Thanks @marcos930807 for the quick response, it worked fine, just awesome!
