### ISSUE TITLE
dialogType: DialogType.NO_HEADER  giving error

### ISSUE THREAD

**Issue by rodriger06** [marcos930807/awesomeDialogs#34]
hi, 

I am using the following code which i copied from your code. 
AwesomeDialog(
                  context: context,
                  headerAnimationLoop: false,
                  dialogType: DialogType.NO_HEADER,
                  tittle: 'No Header',
                  desc:
                  'Dialog description here..................................................',
                  btnOkOnPress: () {
                    debugPrint('OnClcik');
                  },
                  btnOkIcon: Icons.check_circle,
                )..show();

i get an error in android studio on dialogType: DialogType.NO_HEADER that reads:
There is no constant named 'NO_HEADER'  in dialogType

how can i turn off the hearder image?

**Comment by marcos930807** [comment]
Make sure in your puspect.yml you are using the latest version.

**Comment by rodriger06** [comment]
yes, i checked and I have the latest version 1.2.0.  i reran the puspect.yml to get all the packages and still i see the same error

**Comment by marcos930807** [comment]
Ok I will check later stay tuned
