### ISSUE TITLE
Header gone forever when left app for a while and back (both Android and iOS)

### ISSUE THREAD

**Issue by JmyW** [marcos930807/awesomeDialogs#35]
Hi Macro,
It's really awesome package. I very like it. 
I found an issue both happen on Android and iOS, real device and simulator. And reproducible on your demo app.

My steps are following but not 100% reproduce it. In 2 hours test, I found 1 time on iPhone 6s device, 1 time on Android 6.0 device and 1 time on Android 10 emulator.
1. open your demo app
2. click warning dialog
3. cancel it
4. press Home button
5. press Power button
6. stay for while (10 min, 30 min not sure ...)
7. press Power button to resume device
8. reopen demo app
9. click warning dialog
=> the dialog show without header warning icon

It's not easily reproduced by the procedures above. In my experience, the failed rate is around 10%. However indeed.

**Comment by JmyW** [comment]
Any when this phenomenon happened, it's forever until close app.

**Comment by marcos930807** [comment]
Hi @JmyW 
This Only Happens sometime on Debug MODE when usinf Falre Animation, on release works perfect. Dont Worrie.

**Comment by JmyW** [comment]
Excellent! Thank for prompt reply to confirm it.
