### ISSUE TITLE
Gif Format of icons

### ISSUE THREAD

**Issue by b-cancel** [marcos930807/awesomeDialogs#6]
The little icon animations are nice 
but it would be great if you could provide them in gif format
because when you are offline they don't work

additionally, I would like to use them elsewhere

and by default, it might also be a good idea to not have them play after being opened
if you convert them into gifs you could use "flutter_gifimage" plugin to have them just play at the start and never again
having them loop can be distracting

thanks for the help beforehand! and once again great work!

**Comment by marcos930807** [comment]
i @b-cancel tanks for rise and issue.
> but it would be great if you could provide them in gif format
> because when you are offline they don't work
The icon is an animation of flare and works without taking into account connectivity, sometimes you may see the empty icon, that happens in debug mode but it has nothing to do if you are online or offline, and of icon is there. Try without debuging and you will see that it works perfectly.



> and by default, it might also be a good idea to not have them play after being opened

I will add a prop later to control animation loop.

**Comment by marcos930807** [comment]
version 1.1.0 is now released with prop headerAnimationLoop, set this to false only play animation firts time. hope that help.

**Comment by b-cancel** [comment]
@marcos930807 thanks for the help!
since you are so willing and open to suggestions ill toss in another :p
