### ISSUE TITLE
Is it possible to refresh dialog content while it is shown ?

### ISSUE THREAD

**Issue by ben55j** [marcos930807/awesomeDialogs#61]
Hello,

I am using the Dialog with a custom body, to display a counter of quantity (text & buttons).
My problem is that the text widget is not update dynamically while the dialog is shown.
Do you have an idea how I can handle it?

Many thanks,
Benjamin
![AlertDialog](https://user-images.githubusercontent.com/7754473/105188443-345eff00-5b34-11eb-88a9-be59cf8d8a42.png)

**Comment by marcos930807** [comment]
hi @ben55j, thanks for the positive feedback. Make de Body of the dialog a stateful widget, then handle its state using set state or alternative use a stateless with another management state solution like Provider, Bloc etc. If you need more help you can share a piece of code, and I can help you.

**Comment by ben55j** [comment]
Thank you Marco for your fast reply and for your help 🙏🏻! I will try that asap and let you know.

Best
Ben
