### ISSUE TITLE
Feature Request: Make AnimatedButton.buttonTextStyle configurable in AwesomeDialog constructor

### ISSUE THREAD

**Issue by rubenaster** [marcos930807/awesomeDialogs#64]
Morning!

I'd love being able to set the TextStyle of buttons. So far we have the text itself, the icon and the button color in the AwesomeDialog constructor. But I've noticed that the AnimatedButton class takes a TextStyle property and it would be awesome if we could define that in the AwesomeDialog constructor for both buttons.

Currently I need to create a full AnimatedButton by msyself which is somewhat semi-optimal and it could be so much easier.

What do you say? :)

**Comment by marcos930807** [comment]
hi @rubenaster check version 1.3.2. 😁
