### ISSUE TITLE
migrate to null safety 

### ISSUE THREAD

**Issue by kw2019ltd** [marcos930807/awesomeDialogs#65]
Description

All dependencies are migrated to null safety. So we should migrate this package to null safety.
Resources

 https://www.youtube.com/watch?v=eBr5tlumwlg&feature=youtu.be
  https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

**Comment by marcos930807** [comment]
hi @kw2019ltd i am waiting for a dependency on flare_flutter package so, "All dependencies are migrated to null safety." this is not correct.

**Comment by marcos930807** [comment]
When https://pub.dev/packages/flare_flutter lands with null safety, then i will migrate.

**Comment by marcos930807** [comment]
This is Done
