### ISSUE TITLE
FlareHeader default in nullsafety-0 won't be hit, DialogType.INFO reversed

### ISSUE THREAD

**Issue by PcolBP** [marcos930807/awesomeDialogs#67]
![image](https://user-images.githubusercontent.com/67896443/113105253-aec99080-9201-11eb-81a7-6ece8e13011a.png)
As you can see, after upgrade to `awesome_dialog: ^2.0.0-nullsafety.0` INFO dialog reversed.

Warning case looks ok:
![image](https://user-images.githubusercontent.com/67896443/113105597-0cf67380-9202-11eb-8bb3-2dbdd6e0a38e.png)

Changes 

```
case DialogType.INFO:
        return FlareActor(
          "packages/awesome_dialog/assets/flare/info2.flr",
          alignment: Alignment.center,
          fit: BoxFit.cover,
          animation: loop ? 'appear_loop' : 'appear',
          callback: (call) {},
        );
        break;
```

on

```
case DialogType.INFO:
        return FlareActor(
          "packages/awesome_dialog/assets/flare/info.flr",
          alignment: Alignment.center,
          fit: BoxFit.cover,
          animation: 'appear',
          callback: (call) {},
        );
        break;
```

Solved problem.
![image](https://user-images.githubusercontent.com/67896443/113138123-aaaf6a00-9225-11eb-89c0-a26f5d10f2c7.png)

After NNBD Default switch in FlareHeader wont be hit because DialogType can not be null, should we add DialogType.INFO and DialogType.InfoReversed ?

**Comment by itmediacreations** [comment]
Changes 

```
case DialogType.INFO:
        return FlareActor(
          "packages/awesome_dialog/assets/flare/info2.flr",
          alignment: Alignment.center,
          fit: BoxFit.cover,
          animation: loop ? 'appear_loop' : 'appear',
          callback: (call) {},
        );
        break;
```

on

```
case DialogType.INFO:
        return FlareActor(
          "packages/awesome_dialog/assets/flare/info.flr",
          alignment: Alignment.center,
          fit: BoxFit.cover,
          animation: 'appear',
          callback: (call) {},
        );
        break;
```

Solved problem.

**Comment by itmediacreations** [comment]
After NNBD Default switch wont be hit because DialogType can not be null, should we add DialogType.INFO and DialogType.InfoReversed ?

**Comment by marcos930807** [comment]
Hi @itmediacreations the change on DialogType.INFO animation was introduced on version 1.3.0 as per request on #41, the Idea of INFO_REVERSED look great to me.

**Comment by marcos930807** [comment]
> After NNBD Default switch in FlareHeader wont be hit because DialogType can not be null.
This is true but no a big deal since DialogType has a default value of INFO. I will take a look to your PR.

**Comment by itmediacreations** [comment]
> > After NNBD Default switch in FlareHeader wont be hit because DialogType can not be null.
> 
> This is true but no a big deal since DialogType has a default value of INFO. I will take a look to your PR.

Yes it has, but default one is reversed, and can not provide any other DialogType currently to get normal one DialogType.INFO

**Comment by marcos930807** [comment]
> > > After NNBD Default switch in FlareHeader wont be hit because DialogType can not be null.
> > 
> > 
> > This is true but no a big deal since DialogType has a default value of INFO. I will take a look to your PR.
> 
> Yes it has, but default one is reversed, and can not provide any other DialogType currently to get normal looking DialogType.INFO

Your PR is Great, but you do you think you can leave INFO as i and INFOREVERSE as Exclamation !, to be consistent with #41, then you could use INFOREVERSE and have de old INFO behavior.
