### ISSUE TITLE
Shortcut for Buttons OR Focus for Buttons - Goal: desktop

### ISSUE THREAD

**Issue by alberteije** [marcos930807/awesomeDialogs#71]
Hi guys, is it possible to implement shorcuts for buttons or the possibility to focus the buttons (OK and CANCEL) so the user do not need to use mouse. 

This request is for desktop environment.

**Comment by alberteije** [comment]
> 
> 
> Hi guys, is it possible to implement shorcuts for buttons or the possibility to focus the buttons (OK and CANCEL) so the user do not need to use mouse.
> 
> This request is for desktop environment.

Any progress on this?

**Comment by marcos930807** [comment]
closed via #97
