### ISSUE TITLE
Sometimes pressing OK needs 3 times in order to close the popup

### ISSUE THREAD

**Issue by intercretasyo** [marcos930807/awesomeDialogs#83]
Hi,

Sometimes no issue in pressing the OK button. The pop-up will close already. But sometimes I experience where the OK needs to be pressed 3 times in order to close the pop-up. When this issue happens, I notice that the background is closer to black. Then as I keep on pressing OK, the background becomes clearer and clearer.

**Comment by intercretasyo** [comment]
Hi,

I'm not sure but it could be this code that messes the pop-up.
```FocusScope.of(context).unfocus();```

**Comment by marcos930807** [comment]
You need to be aware of what navigator you are using and if is a nested one. Try use the prop useRootNavigator.

**Comment by intercretasyo** [comment]
Hi,

Thanks for your suggestion. I will look into it.
