### ISSUE TITLE
Prevent Default Closing of Dialog on OK Button Click

### ISSUE THREAD

**Issue by Alecckie** [marcos930807/awesomeDialogs#84]
Thank you for your awesome plugin.
When processing a form using the dialog, I'd like to be able to perform some field validation upon **OK Button** click without closing the dialog first, then close the **dialog manually** upon successful validation.

Is there a method like, `closeDialogOnOk:false` with an option to `dialog.dismiss()` for manual dismissing?

**Comment by marcos930807** [comment]
You can use a custom button for ok and cancel, in that case the handle of closing the dialog is up to you using dialog.dismiss()

**Comment by Alecckie** [comment]
Works perfectly ... thanks.
Custom button with `Navigator.pop` works perfectly.

**Comment by Ronjack** [comment]
![image](https://user-images.githubusercontent.com/16069241/145007524-5fb90c59-b486-4191-858e-74d323172cc2.png)

this works for me
