### ISSUE TITLE
Can it return an Awesome dialog as a Widget?

### ISSUE THREAD

**Issue by Retr0sec7** [marcos930807/awesomeDialogs#87]
Hello, I'm currently building an app with bloc/cubit state management. I want to show the dialogs based on a current state, but I can't call them outside a button function.
So is there any way to return it as a Widget ?

`Error: The element type Set<AwesomeDialog> can't be assigned to the list type 'Widget'
`

So for example:

```
...
BlocConsumer<SignInCubit, SignInState>(
          builder: (context, state) => Column(children: <Widget>[
          state.status.isSubmissionInProgress ?
                        //...Show Loading Awesome Dialog
          : Container()

])
```

**Comment by marcos930807** [comment]
@Retr0sec7 a little late maybe but, you could use BlocListener to react to state changes on your cubit or bloc, then show the dialog. Hope that helps.
