### ISSUE TITLE
Trigger Enter key from Keyboard, for Ok btn

### ISSUE THREAD

**Issue by ben55j** [marcos930807/awesomeDialogs#88]
Hello, 

Thank you for this great package.
I am looking to be able to detect the keyboard key "enter" additionally to the Ok button. 
Is there a way to do that ?

I am using this package for the web. 

Many thanks,
Benjamin

**Comment by OutdatedGuy** [comment]
Working on it

**Comment by OutdatedGuy** [comment]
@marcos930807 Please close this issue if resolved
