### ISSUE TITLE
How to delete the space of the title without a title?

### ISSUE THREAD

**Issue by SittiphanSittisak** [marcos930807/awesomeDialogs#89]
Basic code:
AwesomeDialog(
    context: context,
    headerAnimationLoop: false,
    dialogType: DialogType.NO_HEADER,
    padding: EdgeInsets.zero,
   dialogBorderRadius: BorderRadius.only(),
    width: 250,
    body: Text("ABCDEFGHIJKLMNOPQRSTUVWXZY"),
  ).show();

awesome_dialog: ^2.1.2
<img width="143" alt="sca" src="https://user-images.githubusercontent.com/59549741/150687689-855ee522-e6a8-4388-bf7f-46e4fe8a41ef.png">

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1466], locale th-TH)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (2 available)

• No issues found!

**Comment by OutdatedGuy** [comment]
It's not possible at the moment.

Working on it
