### ISSUE TITLE
BIG PROBLEM: animations sometimes not playing

### ISSUE THREAD

**Issue by b-cancel** [marcos930807/awesomeDialogs#9]
I have no idea why... but sometimes the animations just wont play
usually its right after I unplug the cord and am no longer using the phone to debug
I have to close it
then open it again and then it begins working as expected
this is ofcourse a big problem if I'm trying to use this for production

**Comment by marcos930807** [comment]
This happens only en debug mode using hot reaload, it is related to flare i don't know why😅, but in release mode work perfect i use the library on production so dont worry my friend. Tested yourselfe a Release and you will see every think work like a charm.

**Comment by b-cancel** [comment]
@marcos930807 thanks for being so helpful! :)
