### ISSUE TITLE
Anyone know what themedata tag the description text color uses?

### ISSUE THREAD

**Issue by NaMeTaKeN33** [marcos930807/awesomeDialogs#93]
Trying to change the "desc:" color, but not sure what tag to use in the theme.

**Comment by marcos930807** [comment]
You can always use a custom body with a custom text with custom color etc etc. Or change the correct property in themedata (desc is a simple Text widget with no style so must be a bodyText1)

**Comment by NaMeTaKeN33** [comment]
Yeah. I was trying to refrain from using a custom body, but you answer did point me in the right direction. It wasn't bodyText1 for me, however bodyText2 did set the color it. 

Thanks.
